# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/test-pillow-simd',
                'doc_host': 'https://seem.github.io',
                'git_url': 'https://github.com/seem/test-pillow-simd',
                'lib_path': 'test_pillow_simd'},
  'syms': { 'test_pillow_simd.core': {'test_pillow_simd.core.foo': ('core.html#foo', 'test_pillow_simd/core.py')},
            'test_pillow_simd.test': { 'test_pillow_simd.test.test': ('test.html#test', 'test_pillow_simd/test.py'),
                                       'test_pillow_simd.test.test.__init__': ('test.html#test.__init__', 'test_pillow_simd/test.py')}}}